apiVersion: v1
kind: Service
metadata:
  name: auth-service-mysql
  labels:
    app: auth-service-mysql
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30110
  selector:
    app: auth-service-mysql
