apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fedgen-ml
  namespace: default
spec:
  secretName: fedgen-ml-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - fedgen.ml
