# Generated by Django 3.2.5 on 2022-11-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phisAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='unique_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]